import NavBar from "@/components/NavBar";
import Head from "next/head";
import styles from "../styles/home.module.css";
import BountyServices from "@/components/BountyServices";
import AllBounties from "@/components/AllBounties";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className={styles.section}>
          <BountyServices />
          <AllBounties />
        </section>
      </main>
    </>
  );
}
